name: monitor_node2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - blas=1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cuda-cccl_linux-64=12.8.90
  - cuda-crt-dev_linux-64=12.8.93
  - cuda-crt-tools=12.8.93
  - cuda-cudart=12.8.90
  - cuda-cudart-dev=12.8.90
  - cuda-cudart-dev_linux-64=12.8.90
  - cuda-cudart-static=12.8.90
  - cuda-cudart-static_linux-64=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-cuobjdump=12.8.90
  - cuda-cupti=12.8.90
  - cuda-driver-dev_linux-64=12.8.90
  - cuda-nvcc=12.8.93
  - cuda-nvcc-dev_linux-64=12.8.93
  - cuda-nvcc-impl=12.8.93
  - cuda-nvcc-tools=12.8.93
  - cuda-nvcc_linux-64=12.8.93
  - cuda-nvdisasm=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-nvtx=12.8.90
  - cuda-nvvm-dev_linux-64=12.8.93
  - cuda-nvvm-impl=12.8.93
  - cuda-nvvm-tools=12.8.93
  - cuda-version=12.8
  - cudnn=9.17.0.29
  - cyrus-sasl=2.1.28
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fsspec=2025.10.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gmp=6.3.0
  - gmpy2=2.2.2
  - graphite2=1.3.14
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - kernel-headers_linux-64=4.18.0
  - ld_impl_linux-64=2.44
  - libabseil=20250127.0
  - libcublas=12.8.4.1
  - libcudnn=9.17.0.29
  - libcudnn-dev=9.17.0.29
  - libcufft=11.3.3.83
  - libcups=2.4.15
  - libcurand=10.3.9.90
  - libcusolver=11.7.3.90
  - libcusparse=12.5.8.93
  - libdrm=2.4.124
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libllvm19=19.1.7
  - libmlir19=19.1.7
  - libnsl=2.0.0
  - libnvjitlink=12.8.93
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libsanitizer=14.3.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.0.8
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lit=20.1.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - magma=2.9.0=
  - markupsafe=3.0.2
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nccl=2.28.9.1
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=3.0
  - openldap=2.6.10
  - openssl=3.0.18
  - opentelemetry-api=1.38.0
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch=2.5.1
  - pytz=2025.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - setuptools=80.9.0
  - sleef=3.5.1
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - sympy=1.14.0
  - sysroot_linux-64=2.28
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - triton=3.1.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cycler==0.12.1
      - fonttools==4.61.1
      - hf-xet==1.2.0
      - huggingface-hub==1.2.3
      - jsons==1.6.3
      - kiwisolver==1.4.9
      - numpy==1.26.4
      - opencv-python
      - pillow-heif==1.1.1
      - psutil==7.1.3
      - pyparsing==3.3.1
      - shellingham==1.5.4
      - six==1.17.0
      - torchaudio==2.7.1
      - transformers
      - typer-slim==0.20.1
      - typish==1.9.3
      - ultralytics==8.3.241
      - ultralytics-thop==2.0.18
prefix: /home/yang/miniconda3/envs/monitor_node
